env IVCAP_SERVICE_ID=ivcap:service:e5fb1c5f-79ed-55bc-ab86-89aa44c8055c:queue-producer-service \
		IVCAP_PROVIDER_ID=urn:ivcap:provider:e91bb525-83b7-4641-9fb8-b61d084a9b81 \
		IVCAP_ACCOUNT_ID=urn:ivcap:account:e91bb525-83b7-4641-9fb8-b61d084a9b81 \
		IVCAP_CONTAINER=localhost:5000/ivcap.kube/queue_producer_service:fb5dfdc \
	python producer.py --ivcap:print-service-description
"account-id": "urn:ivcap:account:e91bb525-83b7-4641-9fb8-b61d084a9b81"
"description": "A service that publishes synthetic buoy data to a queue."
"id": "ivcap:service:e5fb1c5f-79ed-55bc-ab86-89aa44c8055c:queue-producer-service"
"name": "Queue Producer"
"parameters":
- "description": "Number of data points to publish to the queue."
  "name": "number_of_data_points"
  "type": "int"
- "description": "The identifier of the queue to publish data to."
  "name": "queue_id"
  "type": "string"
"provider-id": "urn:ivcap:provider:e91bb525-83b7-4641-9fb8-b61d084a9b81"
"workflow":
  "basic":
    "command":
    - "python"
    - "/app/service.py"
    "cpu":
      "request": "500m"
    "ephemeral-storage":
      "request": "4Gi"
    "image": "localhost:5000/ivcap.kube/queue_producer_service:fb5dfdc"
    "memory":
      "request": "2Gi"
  "type": "basic"
